env:
  global:
    - CHECKER=https://checker.html5.org/
    - FILES=$(find . -name "*.html")
    - OUTPUT=$(for file in $FILES; do curl -s -F out=gnu -F doc=@$FILE $CHECKER; done)

script:
  - if [ -n "$OUTPUT" ]; then printf "$OUTPUT"; echo; exit 1; fi